# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_auto_20181210_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(default='weixin.jpg', max_length=40),
        ),
    ]
